name: Docker Continuous Integration

description: |
  Build and test code, push to docker registry and send a deployment event

inputs:
  app-checkout-path:
    description: The path to checkout the application repository to during the workflow run
    default: ./app-repo
    required: false
  aws-ecr-login:
    description: A `true` value will attempt to login to ECR
    default: "false"
    required: false
  aws-assume-role:
    description: A `true` value will attempt to assume an AWS IAM Role using ODIC
    default: "false"
    required: false
  aws-iam-role-arn:
    description: The ARN of the AWS IAM Role to assume, required of `aws-iam-assume-role` is `true`
    default: ""
    required: false
  aws-iam-role-session-name:
    description: The name of the AWS assume role session
    default: github-action-ci-docker-workflow
    required: false
  aws-region:
    description: The AWS Region to authenticate with
    default: us-east-1
    required: false
  deploy:
    description: A `true` value will trigger a GitHub deployment
    required: false
    default: "false"
  docker-registry:
    description: Registry where docker image is stored
    required: true
  file:
    description: "Path to the Dockerfile"
    required: false
  image-name:
    description: If present will override derived docker image name
    required: false
    default: ${{ github.event.repository.name }}
  org-access-token:
    description: |
      Secret token for accessing other repos in the GitHub Org. The `secrets` context
      is not available in composite actions and must be passed in from the calling action
    required: false
  run-tests:
    description: A `true` value will result in running tests
    default: "false"
    required: false
  secrets: # https://github.com/docker/build-push-action/blob/master/docs/advanced/secrets.md
    description: List of secrets to expose to the build (eg. key=string, GIT_AUTH_TOKEN=mytoken)
    required: false
  stages:
    description: JSON formatted map of the environments and repos to deploy to based off GitHub event
    required: true
  subdirectory:
    description: Subdirectory of docker file
    required: false
    default: "."
  tests-script:
    description: Script to run during tests step, requires `run-tests` to be set to true, script needs to be executable
    default: tests.sh
    required: false

runs:
  using: composite
  steps:
    - name: Check out repository code
      if: github.event.action != 'closed'
      uses: actions/checkout@v2
      with:
        # Checking the repo out to a separate path seems to avoid a current known issue
        # https://github.com/actions/runner/issues/1300
        path: ${{ inputs.app-checkout-path }}

    #####################################
    # Environment and variable setup
    - name: Set composite level variables
      id: vars
      uses: actions/github-script@v5
      with:
        script: |
          const actionContext = require('./action/lib/actioncontext.js')(this, context, core, github, ${{ toJSON(github) }}, ${{ toJSON(inputs) }}, ${{ toJSON(steps) }})
          const deployment = require('./action/lib/deployment.js')(actionContext)

          var inputs = ${{ toJSON(inputs) }}

          actionContext.setOutput("image_build_enabled", deployment.getInfoCI().image_build_enabled)
          actionContext.setOutput("tests_enabled", "${{ github.event.action }}" != 'closed' && "${{ inputs.run-tests }}" == 'true')
          actionContext.setOutput("image_tag_sha", `${{ inputs.docker-registry }}/${{ inputs.image-name }}:${{ github.sha }}`)

          let aws_assume_role = ("${{ inputs.aws-assume-role }}" == 'true')
          actionContext.setOutput("aws_assume_role", aws_assume_role)

          if (aws_assume_role && "${{ inputs.aws-region }}" == '') {
            core.setFailed('"aws-region" input must be set if "aws-assume-role" is "true"')
          }

          if (aws_assume_role && "${{ inputs.aws-iam-role-arn }}" == '') {
            core.setFailed('"aws-iam-role-arn" input must be set if "aws-assume-role" is "true"')
          }

          actionContext.setOutput("ecr_login_enabled", "${{ github.event.inputs.aws-ecr-login }}" == 'true')
          actionContext.setOutput("public_ecr_enabled", inputs['docker-registry'].startsWith('public.'))

    # #####################################
    # Build Docker image
    # docker context must be created prior to setting up Docker Buildx
    # https://github.com/actions-runner-controller/actions-runner-controller/issues/893
    - name: Set up Docker Context for Buildx
      if: steps.vars.outputs.image_build_enabled == 'true'
      shell: bash
      run: |
        docker context rm buildx-context || true
        docker context create buildx-context

    - name: Set up Docker Buildx (required for docker/build-push-action@v2)
      if: steps.vars.outputs.image_build_enabled == 'true'
      uses: docker/setup-buildx-action@v1
      env:
        DOCKER_CONFIG: /home/runner/.docker
      with:
        endpoint: buildx-context

    - name: Configure AWS Credentials
      if: steps.vars.outputs.aws_assume_role == 'true'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-iam-role-arn }}
        role-session-name: ${{ inputs.aws-iam-role-session-name }}

    - name: Login to Private Amazon ECR
      if: steps.vars.outputs.public_ecr_enabled != 'true'
      uses: aws-actions/amazon-ecr-login@v1

    # aws-actions/amazon-ecr-login does not support public repositories
    # https://github.com/aws-actions/amazon-ecr-login/issues/116
    - name: Login to Public Amazon ECR (via CLI)
      if: steps.vars.outputs.public_ecr_enabled == 'true'
      run: |
        aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin public.ecr.aws
      shell: bash

    - name: Build & Push image to SHA and PR branch
      if: steps.vars.outputs.image_build_enabled == 'true'
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.app-checkout-path }}/${{ inputs.subdirectory }}
        file: ${{ inputs.file }}
        pull: true
        push: true
        # NOTE: when github actions has issues, we have to comment out the cache-* lines
        cache-from: type=gha,scope=blockcluster
        cache-to: type=gha,mode=max,scope=blockcluster
        secrets: |
          ${{ inputs.secrets }}
        tags: |
          ${{ steps.vars.outputs.image_tag_sha }}

    - name: Run test script
      if: steps.vars.outputs.tests_enabled == 'true'
      env:
        IMAGE: ${{ steps.vars.outputs.image_tag_sha }}
      run: |
        ${{ inputs.app-checkout-path }}/${{ inputs.tests-script }}
      shell: bash

    - name: Create deployment
      uses: actions/github-script@main
      if: inputs.deploy == 'true'
      with:
        debug: true
        github-token: ${{ inputs.org-access-token }}
        script: |
          const actionContext = require('./action/lib/actioncontext.js')(this, context, core, github, ${{ toJSON(github) }}, ${{ toJSON(inputs) }}, ${{ toJSON(steps) }})
          const deployment = require('./action/lib/deployment.js')(actionContext)

          let pr_suffix = deployment.getInfoCI().pr_suffix // referenced in inputs.stages
          deployment.newDeployment(JSON.parse(`${{ inputs.stages }}`))

branding:
  icon: target
  color: gray-dark
