name: ecr-public

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  AWS_REGION: us-east-1
  IAM_ROLE_ARN: arn:aws:iam::095356423315:role/cptest-core-ue1-artifacts-ecr-public-github-action
  ECR_REGISTRY: public.ecr.aws/p6x8r6t0/cloudposse

# these permissions are needed to interact with GitHub's OIDC Token endpoint
permissions:
  id-token: write
  contents: read

jobs:
  docker:
    # only run on pull requests so long as they don't come from forks
    if: ( (github.event_name == 'pull_request') && (github.event.pull_request.head.repo.full_name == github.repository) ) || (github.event_name != 'pull_request')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          role-session-name: github-action-ci-docker-workflow
          aws-region: ${{ env.AWS_REGION }}

      # aws-actions/amazon-ecr-login does not support public repositories
      # https://github.com/aws-actions/amazon-ecr-login/issues/116
      - name: Login to Amazon ECR
        run: |
          aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build, Test, and Push to Public ECR Registry
        uses: ./
        with:
          docker-registry: ${{ env.ECR_REGISTRY }}
          run-tests: "true"
          subdirectory: ./test
          tests-script: ./test/test.sh
